### ISSUE TITLE
FancyMenu conflict ?

### ISSUE THREAD

**Issue by lycc193** [RobertSkalko/Age-of-Exile#124]
mod version : farbic-1.16.5-2.1.2
modpack : [Adventure-Pack](https://github.com/SattesKrokodil/Adventure-Pack)
modpack version : 4.5.2
issue : SattesKrokodil/Adventure-Pack#31
When staying in the menu screen,the error is displayed every frame in the log file,two hundred lines of output per second.
```
[00:54:35] [main/INFO]: [STDERR]: java.lang.NullPointerException
[00:54:35] [main/INFO]: [STDERR]: 	at net.minecraft.class_898.method_23168(class_898.java:486)
[00:54:35] [main/INFO]: [STDERR]: 	at com.robertx22.age_of_exile.mixin_methods.RenderMobInfo.renderLivingEntityLabelIfPresent(RenderMobInfo.java:38)
[00:54:35] [main/INFO]: [STDERR]: 	at net.minecraft.class_897.handler$dga001$render(class_897.java:3036)
[00:54:35] [main/INFO]: [STDERR]: 	at net.minecraft.class_897.method_3936(class_897.java)
[00:54:35] [main/INFO]: [STDERR]: 	at net.minecraft.class_922.method_4054(class_922.java:144)
[00:54:35] [main/INFO]: [STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem$MenuPlayerRenderer.render(PlayerEntityCustomizationItem.java:432)
[00:54:35] [main/INFO]: [STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.renderEntityStatic(PlayerEntityCustomizationItem.java:298)
[00:54:35] [main/INFO]: [STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.lambda$renderPlayerEntity$0(PlayerEntityCustomizationItem.java:272)
[00:54:35] [main/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1439)
[00:54:35] [main/INFO]: [STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.renderPlayerEntity(PlayerEntityCustomizationItem.java:271)
[00:54:35] [main/INFO]: [STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.item.playerentity.PlayerEntityCustomizationItem.render(PlayerEntityCustomizationItem.java:218)
[00:54:35] [main/INFO]: [STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.menuhandler.MenuHandlerBase.onRenderPost(MenuHandlerBase.java:1115)
[00:54:35] [main/INFO]: [STDERR]: 	at de.keksuccino.fancymenu.menu.fancy.menuhandler.custom.MainMenuHandler.onRenderPost(MainMenuHandler.java:96)
[00:54:35] [main/INFO]: [STDERR]: 	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
[00:54:35] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:54:35] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[00:54:35] [main/INFO]: [STDERR]: 	at de.keksuccino.konkrete.events.EventHandler.invokeEvent(EventHandler.java:115)
[00:54:35] [main/INFO]: [STDERR]: 	at de.keksuccino.konkrete.events.EventHandler.callEventsFor(EventHandler.java:102)
[00:54:35] [main/INFO]: [STDERR]: 	at net.minecraft.class_757.handler$zlo000$onRenderPre(class_757.java:1977)
[00:54:35] [main/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3192(class_757.java:616)
[00:54:35] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1048)
[00:54:35] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:681)
[00:54:35] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:215)
[00:54:35] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:54:35] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:54:35] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:54:35] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[00:54:35] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[00:54:35] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[00:54:35] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
```

**Comment by RobertSkalko** [comment]
That means the mod is rendering a mob in the menu lol? Will check later.

**Comment by Panderine** [comment]
Yes, it renders a small mob in one corner following the mouse pointer
