### ISSUE TITLE
Error initializing the game

### ISSUE THREAD

**Issue by mealofdoom** [RobertSkalko/Age-of-Exile#24]
Hope I'm submitting this to the right place, sorry if not.

When I start minecraft I get the following error:

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'mmorpg'!
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
    at io.github.giantnuker.fabric.loadcatcher.EntrypointCatcher$LoaderClientReplacement.invokeEntrypoints(EntrypointCatcher.java:142)
    at io.github.giantnuker.fabric.loadcatcher.EntrypointCatcher$LoaderClientReplacement.runEntrypoints(EntrypointCatcher.java:133)
    at io.github.giantnuker.fabric.loadcatcher.EntrypointCatcher$LoaderClientReplacement.run(EntrypointCatcher.java:86)
    at io.github.giantnuker.fabric.loadcatcher.EntrypointCatcher.runEntrypointRedirection(EntrypointCatcher.java:53)
    at net.minecraft.class_310.redirect$zzg000$stopFabricInit(class_310.java:3300)
    at net.minecraft.class_310.<init>(class_310.java:423)
    at net.minecraft.client.main.Main.main(Main.java:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:227)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NullPointerException
    at com.robertx22.age_of_exile.mmorpg.registers.client.RenderLayersRegister.setup(RenderLayersRegister.java:10)
    at com.robertx22.age_of_exile.mmorpg.registers.client.ClientSetup.setup(ClientSetup.java:7)
    at com.robertx22.age_of_exile.mmorpg.init.ClientInit.onInitializeClient(ClientInit.java:14)
    at io.github.giantnuker.fabric.loadcatcher.EntrypointCatcher$LoaderClientReplacement.lambda$invokeEntrypoints$0(EntrypointCatcher.java:150)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
    ... 23 more

**Comment by RobertSkalko** [comment]
Post a full log on a pastebin site and link that. But first, try to update all my mods and see if errors still there.

**Comment by mealofdoom** [comment]
I "fixed" it. Turns out it was a problem with another mod that was out of date. 
Thanks for the quick response and sorry for the inconvenience.
