### ISSUE TITLE
Server spell casting crash. Stackoverflow

### ISSUE THREAD

**Issue by cogrinn** [RobertSkalko/Age-of-Exile#4]
Any time anyone cast a spell

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 7/26/20 9:42 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_638
	at com.robertx22.mine_and_slash.database.data.spells.entities.bases.EntityBaseProjectile.method_18002(EntityBaseProjectile.java:57)
	at net.minecraft.class_3231.method_18757(class_3231.java:224)
	at net.minecraft.class_3231.handler$zjk000$injectSendpacketsOnStartTracking(class_3231.java:563)
	at net.minecraft.class_3231.method_18760(class_3231.java:214)
	at net.minecraft.class_3898$class_3208.updateCameraPosition_(class_3898.java:1962)
	at net.minecraft.class_3898$class_3208.method_18736(class_3898.java:1910)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at net.minecraft.class_3898$class_3208.method_18729(class_3898.java:1921)
	at net.minecraft.class_3898.method_18701(class_3898.java:1020)
	at net.minecraft.class_3215.method_18755(class_3215.java:477)
	at net.minecraft.class_3218.method_18778(class_3218.java:898)
	at net.minecraft.class_3218.method_14175(class_3218.java:829)
	at net.minecraft.class_3218.method_8649(class_3218.java:759)
	at com.robertx22.mine_and_slash.database.data.spells.ProjectileCastOptions.cast(ProjectileCastOptions.java:68)
	at com.robertx22.mine_and_slash.database.data.spells.spell_classes.bases.cast_types.CastProjectile.cast(CastProjectile.java:26)
	at com.robertx22.mine_and_slash.database.data.spells.spell_classes.bases.BaseSpell.cast(BaseSpell.java:225)
	at com.robertx22.mine_and_slash.saveclasses.spells.SpellCastingData.tryCast(SpellCastingData.java:147)
	at com.robertx22.mine_and_slash.saveclasses.spells.SpellCastingData.onTimePass(SpellCastingData.java:97)
	at com.robertx22.mine_and_slash.event_hooks.ontick.OnServerTick.onEndTick(OnServerTick.java:146)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$null$2(ServerTickEvents.java:62)
	at net.minecraft.server.MinecraftServer.handler$zzp000$onEndTick(MinecraftServer.java:1749)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:855)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_638
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Linux (amd64) version 4.19-ovh-xxxx-std-ipv6-64
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1493623224 bytes (1424 MB) / 2850029568 bytes (2718 MB) up to 5726797824 bytes (5461 MB)
	CPUs: 12
	JVM Flags: 4 total; -Xmx6144M -Xms1024M -XX:ParallelGCThreads=2 -XX:ThreadStackSize=512
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		campanion: Campanion 1.1.13+build.35
		cardinal-components: Cardinal Components API 2.4.2
		cardinal-components-base: Cardinal Components API (base) 2.4.2
		cardinal-components-block: Cardinal Components API (blocks) 2.4.2
		cardinal-components-chunk: Cardinal Components API (chunks) 2.4.2
		cardinal-components-entity: Cardinal Components API (entities) 2.4.2
		cardinal-components-item: Cardinal Components API (items) 2.4.2
		cardinal-components-level: Cardinal Components API (world saves) 2.4.2
		cardinal-components-util: Cardinal Components API (utilities) 2.4.2
		cardinal-components-world: Cardinal Components API (worlds) 2.4.2
		cinderscapes: Cinderscapes 1.0.6+build.42-1.16.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.5.6
		curios: Curios API 1.16.1-0.2
		fabric: Fabric API 0.16.0+build.384-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.1.0+013e49d202
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.0+55e0cc5f02
		fabricloader: Fabric Loader 0.9.0+build.204
		fiber: fiber 0.23.0-1
		immersive_portals: Immersive Portals 0.20
		libstructure: Libstructure 1.3
		minecraft: Minecraft 1.16.1
		mmorpg: Age of Exile 1.0.2
		origins: Origins 1.16-0.2.5
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		shapes: Shapes 2.0.0+build.10
		terraform: Terraform 2.1.7+build.31
		terrestria: Terrestria 2.0.4+build.50
		timber: Timber 1.0.3-20w16a
		traverse: Traverse 2.2.14+build.28
	Player Count: 2 / 15; [class_3222['Cogrinn'/187, l='ServerLevel[Hidden Nexus]', x=-314.70, y=66.00, z=-358.70], class_3222['ItThatFled'/194, l='ServerLevel[Hidden Nexus]', x=-248.18, y=57.88, z=-120.99]]
	Data Packs: vanilla (incompatible), fabric/terrestria, fabric/campanion, fabric/traverse, fabric/immersive_portals, fabric/fabric-tool-attribute-api-v1, fabric/curios, fabric/origins, fabric/cinderscapes, fabric/mmorpg (incompatible)
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by RobertSkalko** [comment]
Pushing fix to curseforge.
